version: "3.9"

services:
  api:
    build: .
    container_name: hotel-api
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_TASK_QUEUE=hotel-orchestrator
      - API_BASE=http://api:3000
    depends_on:
      - redis
      - temporal
    networks:
      - orchestrator-net

  worker:
    build: .
    container_name: hotel-worker
    command: npm run worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_TASK_QUEUE=hotel-orchestrator
      - API_BASE=http://api:3000
    depends_on:
      - temporal
      - api
      - redis
    networks:
      - orchestrator-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - orchestrator-net

  postgres:
    image: postgres:12-alpine
    container_name: temporal-postgres
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal     # Postgres uses POSTGRES_PASSWORD
      - POSTGRES_DB=temporal
    ports:
      - "5432:5432"
    networks:
      - orchestrator-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U temporal"]
      interval: 5s
      timeout: 5s
      retries: 5

  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal
    environment:
      - DB=postgres12                  # official value
      - DB_PORT=5432                   # explicit like official file
      - POSTGRES_SEEDS=postgres        # matches your service name
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal          # Temporal expects POSTGRES_PWD
      # - DYNAMIC_CONFIG_FILE_PATH=config/dynamicconfig/development-sql.yaml
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CLI_ADDRESS=temporal:7233
    ports:
      - "7233:7233"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - orchestrator-net

  temporal-ui:
    image: temporalio/ui:latest        # official UI image name
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - temporal
    networks:
      - orchestrator-net

networks:
  orchestrator-net:
    driver: bridge
